package org.grails.cxf.soap;

import java.net.URL;
import javax.annotation.Generated;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.6
 * 2014-10-05T15:45:34.517+05:30
 * Generated source version: 2.6.6
 * 
 */
@WebServiceClient(name = "CustomerServiceWsdlEndpoint", 
                  wsdlLocation = "/home/intelligrape/IdeaProjects/soapApi/src/java/org/grails/cxf/test/soap/CustomerService.wsdl",
                  targetNamespace = "http://test.cxf.grails.org/") 
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-10-05T15:45:34.517+05:30", comments = "Apache CXF 2.6.6")
public class CustomerServiceWsdlEndpoint extends Service {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-10-05T15:45:34.517+05:30")
    public final static URL WSDL_LOCATION;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-10-05T15:45:34.517+05:30")
    public final static QName SERVICE = new QName("http://test.cxf.grails.org/", "CustomerServiceWsdlEndpoint");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-10-05T15:45:34.517+05:30")
    public final static QName CustomerServiceWsdlPort = new QName("http://test.cxf.grails.org/", "CustomerServiceWsdlPort");
    static {
        URL url = CustomerServiceWsdlEndpoint.class.getResource("/home/intelligrape/IdeaProjects/soapApi/src/java/org/grails/cxf/test/soap/CustomerService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(CustomerServiceWsdlEndpoint.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/home/intelligrape/IdeaProjects/soapApi/src/java/org/grails/cxf/test/soap/CustomerService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-10-05T15:45:34.517+05:30")
    public CustomerServiceWsdlEndpoint(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-10-05T15:45:34.517+05:30")
    public CustomerServiceWsdlEndpoint(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-10-05T15:45:34.517+05:30")
    public CustomerServiceWsdlEndpoint() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-10-05T15:45:34.517+05:30")
    public CustomerServiceWsdlEndpoint(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-10-05T15:45:34.517+05:30")
    public CustomerServiceWsdlEndpoint(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-10-05T15:45:34.517+05:30")
    public CustomerServiceWsdlEndpoint(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CustomerServiceWsdlEndpointPortType
     */
    @WebEndpoint(name = "CustomerServiceWsdlPort")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-10-05T15:45:34.517+05:30")
    public CustomerServiceWsdlEndpointPortType getCustomerServiceWsdlPort() {
        return super.getPort(CustomerServiceWsdlPort, CustomerServiceWsdlEndpointPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerServiceWsdlEndpointPortType
     */
    @WebEndpoint(name = "CustomerServiceWsdlPort")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-10-05T15:45:34.517+05:30")
    public CustomerServiceWsdlEndpointPortType getCustomerServiceWsdlPort(WebServiceFeature... features) {
        return super.getPort(CustomerServiceWsdlPort, CustomerServiceWsdlEndpointPortType.class, features);
    }

}
